version: "3.8"

services:
  node-red:
    container_name: ProyectoFinal
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    environment:
      - FLOWS=flows.json
    volumes:
      - node_red_data:/data
    user: "node-red:node-red"
    working_dir: /usr/src/node-red
    networks:
      - node_red_net

volumes:
  node_red_data:

networks:
  node_red_net:
    driver: bridge

networks:
  bridge:
    external: true
